#!/bin/bash
DOCKER_POSTFIX=$(cat postfix)
TAG="latest"
echo $DOCKER_POSTFIX
POSTFIX=$(cat postfix)
if [ "${POSTFIX}" == "-test" ]; then
    BRANCH="devel"
elif  [ "${POSTFIX}" == "-prod" ]; then
    BRANCH="master"
fi
cd secrets ; git pull ; cd ..
curl https://raw.githubusercontent.com/auto-mat/do-prace-na-kole-infrastructure/$BRANCH/docker-compose.yml > docker-compose.yml
sudo docker rmi $(sudo docker images -q)
sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX  docker-compose pull
sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX  docker-compose down
sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX  docker-compose rm
sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX  docker-compose pull
if [ -e worker ]; then
    sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX docker-compose up -d dpnk-worker dpnk-beat
elif [ -e web ]; then
    sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX docker-compose up -d dpnk-web
else
    sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX docker-compose up -d
fi
